<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.Infrastructure.Common\Zhaoxi.MSACommerce.Infrastructure.Common.csproj" />
      <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.Infrastructure.EntityFrameworkCore\Zhaoxi.MSACommerce.Infrastructure.EntityFrameworkCore.csproj" />
      <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.Infrastructure.Redis\Zhaoxi.MSACommerce.Infrastructure.Redis.csproj" />
      <ProjectReference Include="..\Zhaoxi.MSACommerce.SeckillService.Core\Zhaoxi.MSACommerce.SeckillService.Core.csproj" />
    </ItemGroup>
    

    <ItemGroup>
        <PackageReference Include="DotNetCore.CAP" Version="8.3.1" />
        <PackageReference Include="DotNetCore.CAP.Dashboard" Version="8.3.1" />
        <PackageReference Include="DotNetCore.CAP.MySql" Version="8.3.1" />
        <PackageReference Include="DotNetCore.CAP.RabbitMQ" Version="8.3.1" />
      <PackageReference Include="CaptchaGen.NetCore" Version="1.1.2" />
    <PackageReference Include="IdGen.DependencyInjection" Version="3.0.7" />
    </ItemGroup>
    

    <ItemGroup>
      <None Update="Migrations\Scripts\tb_seckill.sql">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
