// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.MSACommerce.OrderService.Infrastructure.Data;

#nullable disable

namespace Zhaoxi.MSACommerce.OrderService.Infrastructure.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260325080506_迁移2")]
    partial class 迁移2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zhaoxi.MSACommerce.OrderService.Core.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id")
                        .HasComment("订单id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ActualPay")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("actual_pay")
                        .HasComment("实付金额。单位:分。如:20007，表示:200元7分");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int(1)")
                        .HasColumnName("payment_type")
                        .HasComment("1、支付宝；2、微信支付");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("receiver")
                        .HasComment("收货人");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("receiver_address")
                        .HasDefaultValueSql("''")
                        .HasComment("收获地址（街道、住址等详细地址）")
                        .UseCollation("utf8_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ReceiverAddress"), "utf8");

                    b.Property<long>("TotalPay")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("total_pay")
                        .HasComment("总金额，单位为分");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("user_id")
                        .HasComment("用户id");

                    b.HasKey("Id");

                    b.ToTable("tb_order", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.OrderService.Core.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id")
                        .HasComment("订单明细项id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Image")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("image")
                        .HasDefaultValueSql("''")
                        .HasComment("商品图片");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title")
                        .HasComment("商品标题");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("order_id")
                        .HasComment("订单id");

                    b.Property<long>("Price")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("price")
                        .HasComment("价格,单位：分");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(11)")
                        .HasColumnName("quantity")
                        .HasComment("购买数量");

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("sku_id")
                        .HasComment("sku商品id");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("own_spec")
                        .HasDefaultValueSql("''")
                        .HasComment("商品动态属性键值集");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("tb_order_detail", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.OrderService.Core.Entities.OrderInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id")
                        .HasComment("订单id");

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime")
                        .HasColumnName("close_time")
                        .HasComment("交易关闭时间");

                    b.Property<DateTime?>("ConsignTime")
                        .HasColumnType("datetime")
                        .HasColumnName("consign_time")
                        .HasComment("发货时间");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("create_time")
                        .HasComment("订单创建时间");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time")
                        .HasComment("交易完成时间");

                    b.Property<DateTime?>("PaymentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_time")
                        .HasComment("付款时间");

                    b.Property<int>("Status")
                        .HasColumnType("int(1)")
                        .HasColumnName("status")
                        .HasComment("状态：1、未付款 2、已付款,未发货 3、已发货,未确认 4、交易成功 5、交易关闭");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("tb_order_info", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.OrderService.Core.Entities.OrderDetail", b =>
                {
                    b.HasOne("Zhaoxi.MSACommerce.OrderService.Core.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.OrderService.Core.Entities.OrderInfo", b =>
                {
                    b.HasOne("Zhaoxi.MSACommerce.OrderService.Core.Entities.Order", "Order")
                        .WithOne("OrderInfo")
                        .HasForeignKey("Zhaoxi.MSACommerce.OrderService.Core.Entities.OrderInfo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.OrderService.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
