// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.MSACommerce.StockService.Infrastructure.Data;

#nullable disable

namespace Zhaoxi.MSACommerce.StockService.Infrastructure.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20241116090714_InsertData")]
    partial class InsertData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zhaoxi.MSACommerce.StockService.Core.Entities.SkuStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id")
                        .HasComment("商品SKU Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AvailQty")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("avail_qty")
                        .HasComment("可用数量");

                    b.Property<long>("ResvQty")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("resv_qty")
                        .HasComment("预留数量");

                    b.Property<long>("TotalQty")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("total_qty")
                        .HasComment("库存总数量");

                    b.HasKey("Id");

                    b.ToTable("tb_sku_stock", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.StockService.Core.Entities.StockResv", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id")
                        .HasComment("预留记录id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExprTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expr_time")
                        .HasComment("预留过期时间");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("order_id")
                        .HasComment("关联订单ID");

                    b.Property<long>("ResvQty")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("resv_qty")
                        .HasComment("预留数量");

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint(20)");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.ToTable("tb_stock_resv", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.StockService.Core.Entities.StockResv", b =>
                {
                    b.HasOne("Zhaoxi.MSACommerce.StockService.Core.Entities.SkuStock", "SkuStock")
                        .WithMany("StockResve")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkuStock");
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.StockService.Core.Entities.SkuStock", b =>
                {
                    b.Navigation("StockResve");
                });
#pragma warning restore 612, 618
        }
    }
}
