// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.MSACommerce.SeckillService.Infrastructure.Data;

#nullable disable

namespace Zhaoxi.MSACommerce.SeckillService.Infrastructure.Migrations
{
    [DbContext(typeof(SecKillDbContext))]
    [Migration("20241204153639_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zhaoxi.MSACommerce.SeckillService.Core.Entities.SecKillProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    b.Property<long>("CostPrice")
                        .HasColumnType("bigint(15)")
                        .HasColumnName("cost_price")
                        .HasComment("秒杀价格");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time")
                        .HasComment("结束时间");

                    b.Property<string>("Introduction")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("introduction")
                        .HasComment("描述");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name")
                        .HasComment("商品名称");

                    b.Property<int>("Num")
                        .HasColumnType("int")
                        .HasColumnName("num")
                        .HasComment("秒杀商品数");

                    b.Property<long>("Price")
                        .HasColumnType("bigint(15)")
                        .HasColumnName("price")
                        .HasComment("原价格");

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("sku_id");

                    b.Property<string>("SmallPic")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("small_pic")
                        .HasComment("商品缩略图");

                    b.Property<long>("SpuId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("spu_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time")
                        .HasComment("开始时间");

                    b.Property<int>("StockCount")
                        .HasColumnType("int")
                        .HasColumnName("stock_count")
                        .HasComment("剩余库存数");

                    b.HasKey("Id");

                    b.ToTable("tb_seckill_product", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
