// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.MSACommerce.SeckillService.Infrastructure.Data;

#nullable disable

namespace Zhaoxi.MSACommerce.SeckillService.Infrastructure.Migrations
{
    [DbContext(typeof(SecKillDbContext))]
    [Migration("20241207113305_AddSeckillOrder")]
    partial class AddSeckillOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zhaoxi.MSACommerce.SeckillService.Core.Entities.SecKillProduct", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    b.Property<long>("CostPrice")
                        .HasColumnType("bigint(15)")
                        .HasColumnName("cost_price")
                        .HasComment("秒杀价格");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time")
                        .HasComment("结束时间");

                    b.Property<string>("Introduction")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("introduction")
                        .HasComment("描述");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name")
                        .HasComment("商品名称");

                    b.Property<int>("Num")
                        .HasColumnType("int")
                        .HasColumnName("num")
                        .HasComment("秒杀商品数");

                    b.Property<long>("Price")
                        .HasColumnType("bigint(15)")
                        .HasColumnName("price")
                        .HasComment("原价格");

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("sku_id");

                    b.Property<string>("SmallPic")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("small_pic")
                        .HasComment("商品缩略图");

                    b.Property<long>("SpuId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("spu_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time")
                        .HasComment("开始时间");

                    b.Property<long>("StockCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stock_count")
                        .HasComment("剩余库存数");

                    b.HasKey("Id");

                    b.ToTable("tb_seckill_product", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.SeckillService.Core.Entities.SeckillOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    b.Property<long>("ActualPay")
                        .HasPrecision(10, 2)
                        .HasColumnType("bigint")
                        .HasColumnName("money")
                        .HasComment("支付金额");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("create_time")
                        .HasComment("创建时间");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PayTime")
                        .HasColumnType("datetime")
                        .HasColumnName("pay_time")
                        .HasComment("支付时间");

                    b.Property<string>("Receiver")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("receiver")
                        .HasComment("收货人");

                    b.Property<string>("ReceiverAddress")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("receiver_address")
                        .HasComment("收货人地址");

                    b.Property<string>("ReceiverMobile")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("receiver_mobile")
                        .HasComment("收货人电话");

                    b.Property<long>("SeckillId")
                        .HasColumnType("bigint")
                        .HasColumnName("seckill_id")
                        .HasComment("秒杀商品ID");

                    b.Property<int>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .IsFixedLength()
                        .HasComment("状态，0未支付，1已支付");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("transaction_id")
                        .HasComment("交易流水");

                    b.Property<long>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("用户");

                    b.HasKey("Id");

                    b.ToTable("tb_seckill_order", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
