// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.MSACommerce.CategoryService.Infrastructure.Data;

#nullable disable

namespace Zhaoxi.MSACommerce.CategoryService.Infrastructure.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    [Migration("20260319081220_商品")]
    partial class 商品
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CategoryCategoryBrands", b =>
                {
                    b.Property<long>("BrandsId")
                        .HasColumnType("bigint(20)");

                    b.Property<long>("CategoriesId")
                        .HasColumnType("bigint(20)");

                    b.HasKey("BrandsId", "CategoriesId");

                    b.HasIndex("CategoriesId");

                    b.ToTable("CategoryCategoryBrands");
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id")
                        .HasComment("品类id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsParent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_parent")
                        .HasComment("是否为父节点，0为否，1为是");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name")
                        .HasComment("品类名称");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("parent_id")
                        .HasComment("父类id,顶级类填0");

                    b.Property<int>("Sort")
                        .HasColumnType("int(4)")
                        .HasColumnName("sort")
                        .HasComment("排序指数，越小越靠前");

                    b.HasKey("Id");

                    b.ToTable("tb_category", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.CategoryBrands", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("brand_id")
                        .HasComment("品牌id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("category_id")
                        .HasComment("品类id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "BrandId")
                        .IsUnique();

                    b.ToTable("tb_category_brands", (string)null);
                });

            modelBuilder.Entity("CategoryCategoryBrands", b =>
                {
                    b.HasOne("Zhaoxi.MSACommerce.CategoryService.Core.Entities.CategoryBrands", null)
                        .WithMany()
                        .HasForeignKey("BrandsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
