<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\pakages\Zhaoxi.MSACommerce.CommonServiceClient\Zhaoxi.MSACommerce.CommonServiceClient.csproj" />
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.SharedKernel\Zhaoxi.MSACommerce.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.UseCases.Common\Zhaoxi.MSACommerce.UseCases.Common.csproj" />
        <ProjectReference Include="..\Zhaoxi.MSACommerce.SearchService.Core\Zhaoxi.MSACommerce.SearchService.Core.csproj" />
        <ProjectReference Include="..\Zhaoxi.MSACommerce.SearchService.Infrastructure\Zhaoxi.MSACommerce.SearchService.Infrastructure.csproj" />
    </ItemGroup>
</Project>
