<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.SharedEvent\Zhaoxi.MSACommerce.SharedEvent.csproj" />
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.SharedKernel\Zhaoxi.MSACommerce.SharedKernel.csproj" />
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.UseCases.Common\Zhaoxi.MSACommerce.UseCases.Common.csproj" />
        <ProjectReference Include="..\Zhaoxi.MSACommerce.CartService.Core\Zhaoxi.MSACommerce.CartService.Core.csproj" />
        <ProjectReference Include="..\Zhaoxi.MSACommerce.CartService.Infrastructure\Zhaoxi.MSACommerce.CartService.Infrastructure.csproj" />
    </ItemGroup>
    
</Project>
