<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.Infrastructure.Common\Zhaoxi.MSACommerce.Infrastructure.Common.csproj" />
        <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.Infrastructure.EntityFrameworkCore\Zhaoxi.MSACommerce.Infrastructure.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\Zhaoxi.MSACommerce.StockService.Core\Zhaoxi.MSACommerce.StockService.Core.csproj" />
    </ItemGroup>
    
</Project>
