<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.SharedKernel\Zhaoxi.MSACommerce.SharedKernel.csproj" />
      <ProjectReference Include="..\..\..\..\shared\Zhaoxi.MSACommerce.UseCases.Common\Zhaoxi.MSACommerce.UseCases.Common.csproj" />
      <ProjectReference Include="..\Zhaoxi.MSACommerce.UserService.Core\Zhaoxi.MSACommerce.UserService.Core.csproj" />
      <ProjectReference Include="..\Zhaoxi.MSACommerce.UserService.Infrastructure\Zhaoxi.MSACommerce.UserService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
