<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Zhaoxi.MSACommerce.Infrastructure.Common\Zhaoxi.MSACommerce.Infrastructure.Common.csproj" />
      <ProjectReference Include="..\Zhaoxi.MSACommerce.SharedKernel\Zhaoxi.MSACommerce.SharedKernel.csproj" />
      <ProjectReference Include="..\Zhaoxi.MSACommerce.UseCases.Common\Zhaoxi.MSACommerce.UseCases.Common.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Com.Ctrip.Framework.Apollo.Configuration" Version="2.11.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Apollo相关配置流程\" />
    </ItemGroup>
</Project>
