// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.MSACommerce.ProductService.Infrastructure.Data;

#nullable disable

namespace Zhaoxi.MSACommerce.ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20241103084451_InsertData")]
    partial class InsertData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Sku", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Images")
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("images")
                        .HasComment("商品的图片，多个图片以‘,’分割");

                    b.Property<string>("Indexes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("indexes")
                        .HasDefaultValueSql("''")
                        .HasComment("sku规格在spu规格中的对应下标组合");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name")
                        .HasComment("商品名称");

                    b.Property<long>("Price")
                        .HasColumnType("bigint(15)")
                        .HasColumnName("price")
                        .HasComment("销售价格，单位为分");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("spec")
                        .HasDefaultValueSql("''")
                        .HasComment("规格参数键值对，json格式");

                    b.Property<long>("SpuId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("spu_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SpuId");

                    b.ToTable("tb_sku", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Spu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BrandId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("brand_id")
                        .HasComment("商品所属品牌id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("category_id")
                        .HasComment("所属品类id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description")
                        .HasComment("产品描述");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name")
                        .HasComment("产品名称");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasComment("是否在售，0未售，1在售");

                    b.HasKey("Id");

                    b.ToTable("tb_spu", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.SpuDetail", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("introduction")
                        .HasComment("商品介绍");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("parameter")
                        .HasComment("商品参数");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("spec")
                        .HasComment("商品规格");

                    b.HasKey("Id");

                    b.ToTable("tb_spu_detail", (string)null);
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Sku", b =>
                {
                    b.HasOne("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Spu", null)
                        .WithMany("Skus")
                        .HasForeignKey("SpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.SpuDetail", b =>
                {
                    b.HasOne("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Spu", null)
                        .WithOne("Detail")
                        .HasForeignKey("Zhaoxi.MSACommerce.CategoryService.Core.Entities.SpuDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zhaoxi.MSACommerce.CategoryService.Core.Entities.Spu", b =>
                {
                    b.Navigation("Detail")
                        .IsRequired();

                    b.Navigation("Skus");
                });
#pragma warning restore 612, 618
        }
    }
}
